# Generated by Django 6.1.2 on 2026-10-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_split_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='emoji',
        ),
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(default='wallet', max_length=24),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('currency', models.CharField(choices=[('USD', 'USD ($)'), ('INR', 'INR (₹)'), ('EUR', 'EUR (€)'), ('GBP', 'GBP (£)'), ('JPY', 'JPY (¥)'), ('AUD', 'AUD (A$)'), ('CAD', 'CAD (C$)'), ('AED', 'AED (د.إ)')], default='USD', max_length=3)),
                ('date_format', models.CharField(choices=[('relative', 'Relative (e.g. 2 days ago)'), ('dmy', 'DD/MM/YYYY'), ('mdy', 'MM/DD/YYYY'), ('iso', 'YYYY-MM-DD')], default='relative', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
