# Generated by Django 6.1.2 on 2026-10-07 17:28

import secrets

from django.db import migrations

ALPHABET = 'abcdefghjkmnpqrstuvwxyz23456789'


def backfill(apps, schema_editor):
    Group = apps.get_model('expenses', 'Group')
    Member = apps.get_model('expenses', 'Member')
    GroupMembership = apps.get_model('expenses', 'GroupMembership')
    GroupInvite = apps.get_model('expenses', 'GroupInvite')

    used_codes = set(GroupInvite.objects.values_list('code', flat=True))

    def new_code():
        while True:
            code = ''.join(secrets.choice(ALPHABET) for _ in range(8))
            if code not in used_codes:
                used_codes.add(code)
                return code

    for group in Group.objects.all():
        owner = group.owner

        # Admin membership for the group creator, backed by a Member for them.
        if not GroupMembership.objects.filter(group=group, user=owner).exists():
            member = Member.objects.filter(owner=owner, user=owner).first()
            if member is None:
                name = owner.username
                if Member.objects.filter(owner=owner, name=name).exists():
                    name = f'{owner.username} (@{owner.username})'
                member = Member.objects.create(owner=owner, user=owner, name=name)
            GroupMembership.objects.create(
                group=group, user=owner, member=member, role='admin',
            )

        # Existing standalone (name-only) members that already appear in this
        # group's expenses stay splittable: attach them as local members.
        member_ids = set()
        for expense in group.expenses.all():
            member_ids.update(expense.splits.values_list('member_id', flat=True))
            if expense.paid_by_id:
                member_ids.add(expense.paid_by_id)
        member_ids.update(group.last_splitters.values_list('id', flat=True))
        for member in Member.objects.filter(id__in=member_ids, user__isnull=True):
            member.local_groups.add(group)

        # Give each group a stable invite code up front.
        if not GroupInvite.objects.filter(group=group).exists():
            GroupInvite.objects.create(group=group, code=new_code())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_member_local_groups_member_user_groupinvite_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
